// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBREPdhCy6UIkRyJO1ao1FR4dOtAjMDzM',
    appId: '1:77618770405:web:d0b8d5337f6636cf17bf0c',
    messagingSenderId: '77618770405',
    projectId: 'myfluttertest-f7760',
    authDomain: 'myfluttertest-f7760.firebaseapp.com',
    storageBucket: 'myfluttertest-f7760.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1PIBVISRDMo0QGBVITYAFMAD4NPW2vL8',
    appId: '1:77618770405:android:dc3d85d2af6c853417bf0c',
    messagingSenderId: '77618770405',
    projectId: 'myfluttertest-f7760',
    storageBucket: 'myfluttertest-f7760.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjt_i5w-K6QDYrPXg-SONfH-fTYfVKEQo',
    appId: '1:77618770405:ios:4530d67f4f53f7e417bf0c',
    messagingSenderId: '77618770405',
    projectId: 'myfluttertest-f7760',
    storageBucket: 'myfluttertest-f7760.appspot.com',
    iosClientId: '77618770405-rfqt929tou30lkesmgeh87qmcp8q5fph.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjt_i5w-K6QDYrPXg-SONfH-fTYfVKEQo',
    appId: '1:77618770405:ios:4530d67f4f53f7e417bf0c',
    messagingSenderId: '77618770405',
    projectId: 'myfluttertest-f7760',
    storageBucket: 'myfluttertest-f7760.appspot.com',
    iosClientId: '77618770405-rfqt929tou30lkesmgeh87qmcp8q5fph.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireTest',
  );
}
